### ISSUE TITLE
Error when displaying race seed window

### ISSUE THREAD

**Issue by Naii-the-Baf** [Schwork-Corruption/corruptovania#12]
While generating a race seed, I keep getting an error.

```
Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "randovania\gui\widgets\generate_game_widget.py", line 109, in generate_new_layout_race
  File "randovania\gui\widgets\generate_game_widget.py", line 140, in generate_new_layout
  File "randovania\gui\widgets\generate_game_widget.py", line 194, in generate_layout_from_permalink
  File "randovania\gui\widgets\generate_game_widget.py", line 46, in persist_layout
  File "randovania\layout\layout_description.py", line 264, in save_to_file
  File "randovania\layout\layout_description.py", line 222, in as_json
  File "randovania\lib\obfuscator.py", line 40, in obfuscate_json
  File "randovania\lib\obfuscator.py", line 36, in obfuscate
  File "randovania\lib\obfuscator.py", line 30, in _get_fernet
  File "cryptography\fernet.py", line 40, in __init__
ValueError: Fernet key must be 32 url-safe base64-encoded bytes.
```

The seed does generate, but it seems to have trouble displaying it.
Seeds with spoilers have no issues, it seems to be just race seeds.

**Comment by Miepee** [comment]
Fixed.
Not in a commit, because turns out there was an environment variable for CI missing.

**Comment by SchwartzGandhi** [comment]
Hear the Word of O-Lir
