### ISSUE TITLE
`input_path` and `output_path` missing in versioned_config.json

### ISSUE THREAD

**Issue by Samuel6710** [Schwork-Corruption/corruptovania#20]
Error received when trying to open the export window on Corruptovania 1.3.0c. 

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "sentry_sdk\integrations\asyncio.py", line 55, in _coro_creating_hub_and_span
  File "sentry_sdk\utils.py", line 1690, in reraise
  File "sentry_sdk\integrations\asyncio.py", line 53, in _coro_creating_hub_and_span
  File "randovania\gui\game_details\game_details_window.py", line 184, in _export_iso
  File "randovania\games\prime3\gui\dialog\game_export_dialog.py", line 69, in __init__
  File "randovania\games\prime3\gui\dialog\game_export_dialog.py", line 137, in _on_update_output_format
  File "pathlib.py", line 654, in with_suffix
ValueError: WindowsPath('.') has an empty name
![image](https://github.com/user-attachments/assets/4a1db27f-ad74-4127-8199-d11e15ce72ae)

**Comment by Samuel6710** [comment]
I do not receive this error when opening the export window on 1.2.9.

**Comment by SchwartzGandhi** [comment]
issue seems to be stemming from not caching settings correctly, creating a dummy path in the config json is a good workaround but, more than likely there just isnt support for a default path.
will leave issue open for now

**Comment by Miepee** [comment]
skill issue when trying to extract the zip
