### ISSUE TITLE
v1.3.0c Fails to export the game (exit code 3221225781)

### ISSUE THREAD

**Issue by Piefanatic555** [Schwork-Corruption/corruptovania#21]
Installed the v1.3.0c release for Windows and was not able to export the game correctly using the core or patched versions to either format. Error log below. Saving the spoiler file is still working as intended.

> Traceback (most recent call last):
>   File "randovania\gui\lib\game_exporter.py", line 52, in export_game
>   File "randovania\gui\lib\background_task_mixin.py", line 76, in run_in_background_async
>   File "randovania\gui\lib\background_task_mixin.py", line 68, in work
>   File "randovania\gui\lib\game_exporter.py", line 42, in work
>   File "randovania\exporter\game_exporter.py", line 84, in export_game
>   File "randovania\games\prime3\exporter\game_exporter.py", line 67, in _do_export_game
>   File "subprocess.py", line 571, in run
> subprocess.CalledProcessError: Command '[WindowsPath('D:/Emulators/corruptovania-1.3.0/_internal/data/gollop_mp3_patcher/nodtool/nodtool.exe'), 'extract', WindowsPath('D:/Emulators/Randomizers/MP3Randomizer/iso/mp3_patched.iso'), 'C:\\Users\\***\\AppData\\Local\\Temp\\tmpul5jnse2']' returned non-zero exit status 3221225781.

Used the same spoiler file in v1.2.8c and v1.2.9c and both versions were able to export successfully.

**Comment by Piefanatic555** [comment]
Took a peek at the contents of the new version and the most obvious change I can see is the addition of a bunch of .dll files that appear related to Cygwin. Is it possible that there's a missing reference or dependency in these somewhere that's causing nodtool to fail?
![image](https://github.com/user-attachments/assets/a766eed1-a179-4519-803e-205a96dcb039)

**Comment by Piefanatic555** [comment]
Yeah that seems to be the problem. I copied over the entire gollop_mp3_patcher folder and overwrote the same folder in 1.3.0.
It's now able to export both formats, but I can't verify if the WBFS works for console purposes.
